### ISSUE TITLE
emitParticle support?

### ISSUE THREAD

**Issue by ArondeParon** [vasturiano/3d-force-graph-vr#14]
Is there a specific reason why the 2d and 3d variants have support for `emitParticle()`, while this one does not?

This would be a really nice addition to generate more real-time visualizations.

**Comment by vasturiano** [comment]
@ArondeParon thanks for reaching out. `emitParticle` is not supported in the VR variant due to a technicality with the data communication through `aframe`. Due to the manner in which props are injected to the aframe component they have to be cloned rather than referenced. This makes the link object references not match when looking for that particular item in the `graphData` structure internal to [three-forcegraph](https://github.com/vasturiano/three-forcegraph).

This is the reason why that functionality was excluded from this module. You can see the removal commit here: https://github.com/vasturiano/3d-force-graph-vr/commit/d81215644a424bdc95af49affd4d96ab16d6b520

**Comment by ArondeParon** [comment]
Ah that is too bad. Thanks for the explanation!
