### ISSUE TITLE
Make graph more interactive by allowing presentation at a more human scale

### ISSUE THREAD

**Issue by damned** [vasturiano/3d-force-graph-vr#19]
When I open up the examples in VR (Oculus quest) the graph is seemingly rendered large and far away (as if laid out across a sports field) compared to my scale (room or table-top size) as i move around in the real world.

Being able to physically move or look around as you would a physical object would make it more understandable.

If the scale could be easily configured with a scalar value that should cover it.

I did simulate this by setting scale on the forcegraph component really small (to '0.01 0.01 0.01') but it has side effects (requiring zooming in to make text readable which makes it vary jumpy if moving with controls).

Having looked into the underlying code, to do this properly i'm guessing it might require configuration of the charge forces down in d3-force-3d?

**Comment by vasturiano** [comment]
@damned thanks for reaching out.

I believe setting `scale="0.1 0.1 0.1"` on the aframe forcegraph component is the appropriate way of reducing the size of the whole graph, because everything is reduced proportionally which should probably be the intention here.

If the controls movement speed is too jumpy for the smaller size, those settings can be adjusted too, via the `movement-controls` > `speed: 7` attribute.

I don't think you'll need to modify the forces just for the purposes of presentation. If the intent is to fill in the empty space more, you can always increase the visible size of the nodes.

Further, if you wish to do a lot of modifications to the way the scene in this module is setup I'd encourage you to go one level lower and consume from [aframe-forcegraph-component](https://github.com/vasturiano/aframe-forcegraph-component) directly. That way you can setup your scene with full flexibility.
This module is just a default setup of a scene around the aframe component for the ease of convenience.

**Comment by damned** [comment]
thank you for the detailed help - this covers everything i was having trouble with :)
