### ISSUE TITLE
Errors when trying to swap out 3d forcegraph for 3d forcegraph VR 

### ISSUE THREAD

**Issue by malani-art** [vasturiano/3d-force-graph-vr#26]
Hi!

We are trying to upgrade this project https://github.com/mister-blanket/blood-lines to replace 3d-force-graph with 3d-force-graph-vr. We installed the latest react-force-graph-vr and replaced the import here https://github.com/mister-blanket/blood-lines/blob/master/src/Graph.js#L4 with `import ForceGraphVR from "react-force-graph-vr"` and the module here https://github.com/mister-blanket/blood-lines/blob/master/src/Graph.js#L423 with `ForceGraphVR`.  Here are the errors we are getting.

![Screenshot from 2021-11-15 17-08-47](https://user-images.githubusercontent.com/79165958/141873236-3a75e86a-39ba-46d1-aa3c-64728e492f93.png)

Do you have a recommendation on the right combination of versions we should use or a path to upgrade this older project to enable VR?

Thank you!

**Comment by vasturiano** [comment]
@malani-art it's difficult to be precise without a specific repro reduced example.

But, it looks like the first issue you're encountering is that there is no `scene()` method on the VR module. That is to be expected, you can't extend the Three scene the same way you do on the 3D module, because it's using `Aframe` not `ThreeJS` directly.

**Comment by malani-art** [comment]
@vasturiano Hi i was able to get it to work by using import ForceGraphVR from "react-force-graph-3d";
